services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RESTRICT_FILE_ACCESS_TO=""
      - NODES_EXCLUDE=[]
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      - WEBHOOK_URL=http://${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}

    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    labels:
      - 'traefik.http.routers.n8n.rule=HostRegexp(`^n8n\..+$`) || PathPrefix(`/n8n`)'
      - "traefik.http.middlewares.n8n-remove-prefix.stripprefix.prefixes=/n8n"
      - "traefik.http.routers.n8n.middlewares=n8n-remove-prefix"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=traefik-network"
    networks:
      - default
      - traefik-network
volumes:
  n8n_data:
networks:
  traefik-network:
    external: true
